# Generated by Django 4.2.6 on 2023-11-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAINDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon nomresi')),
                ('location', models.CharField(max_length=255, verbose_name='mekan')),
                ('mesage', models.CharField(max_length=255, verbose_name='mesage')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'esas detal',
                'verbose_name_plural': 'esas detallar',
                'ordering': ('email',),
            },
        ),
    ]
