# Generated by Django 4.2.6 on 2023-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_maindetails_mesage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='xidmet'),
        ),
    ]
