# Generated by Django 4.2.6 on 2023-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='telefon nomresi'),
        ),
    ]
