# Generated by Django 4.2.6 on 2023-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_contact_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_service',
            field=models.CharField(blank=True, choices=[('temir', 'Temir'), ('berpa', 'Berpa'), ('salam', 'Salam'), ('sagol', 'Sagol')], max_length=255, null=True),
        ),
    ]
